version: '3.3'
services:
  app:
    image: flask_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    restart: always
    ports:
        - 3308:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
        MYSQL_USER: myuser
        MYSQL_PASSWORD: mypaswd
